### ISSUE TITLE
Cannot update to latest firmware on T14s Gen 1

### ISSUE THREAD

**Issue by jrop** [fwupd/firmware-lenovo#277]
**Describe the bug**

I have tried several times to update to the latest firmware on my Lenovo ThinkPad T14s AMD Gen 1 laptop, and each time the update appears to run to completion with no apparent errors, but it still shows me at the end that an update is available.

Most recently, I downloaded an updated BIOS *.cab file directly from Lenovo's website (after putting my model # in to make sure I was downloading the correct one), plugged my laptop into AC power, and ran `sudo fwupdmgr install Lenovo-ThinkPad-X13-T14s-AMD-SystemFirmware-1.41.cab`.  The system rebooted, pausing during the process (so I figured it was doing something), but when it booted up on its own, it still shows that I have updates to apply.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
runtime   org.freedesktop.fwupd         1.8.0
runtime   org.freedesktop.fwupd-efi     1.0
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    5.19.16-76051916-generic
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         1.8.0
runtime   org.freedesktop.gusb          0.3.10
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

I'm on Pop!_OS, so it came installed with the system.
<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
20UHCTO1WW
│
├─Unknown Device:
│     Device ID:          f685512aa07369c9e77742acef941d779d31e766
│     GUID:               37b440a9-2473-5087-a39b-db84f32a8ed8 ← GPIO\ID_AMDI0030:00
│
├─Integrated Camera:
│     Device ID:          54f0d9041b6c5438c7ff825f5139559c5ca1b222
│     Current version:    58.18
│     Vendor:             Chicony Electronics Co.,Ltd. (USB:0x04F2)
│     Serial Number:      0001
│     GUIDs:              95b07a8e-2063-5025-80b5-1fcf4ca8e9e3 ← USB\VID_04F2&PID_B6CB
│                         08c6b922-0e9b-5283-9e1a-2f5a549abf8e ← USB\VID_04F2&PID_B6CB&REV_5818
│     Device Flags:       • Updatable
│
├─Ryzen 7 PRO 4750U with Radeon Graphics:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Vendor:             AMD
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         997104da-ec11-5e04-9d94-ac5501fbf609 ← CPUID\PRO_0&FAM_17
│                         1f2e0c2f-e078-5fcb-a8de-f78eff9a470a ← CPUID\PRO_0&FAM_17&MOD_60
│                         5fd5eb41-dd4a-5742-8448-861eaaa61cf8 ← CPUID\PRO_0&FAM_17&MOD_60&STP_1
│     Device Flags:       • Internal device
│
├─Sabrent:
│     Device ID:          71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Summary:            NVM Express solid state drive
│     Current version:    RKT303.3
│     Vendor:             Phison Electronics Corporation (NVME:0x1987)
│     Serial Number:      203E0705051500170993
│     GUIDs:              a44eb54c-5441-56f2-8cc0-5e48964c6457 ← NVME\VEN_1987&DEV_5012
│                         8cb1e2fe-eb01-5508-9fb3-98add4bb7c34 ← NVME\VEN_1987&DEV_5012&REV_01
│                         94e27f4a-86e3-53a2-a728-18db5dd2be18 ← NVME\VEN_1987&DEV_5012&SUBSYS_19875012
│                         38d64a8a-1cd1-589c-9f70-b0b9c4379c43 ← NVME\VEN_1987&DEV_5012&SUBSYS_19875012&REV_01
│                         562f2e08-972d-5a08-8da1-a44ab1304cf8 ← Sabrent
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs shutdown after installation
│                         • Device is usable for the duration of the update
│
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    0.1.5
│ │   Vendor:             Lenovo (DMI:LENOVO)
│ │   Update State:       Success
│ │   Update Message:     The computer will be restarted automatically after updating BIOS completely. Do NOT turn off your computer or remove the AC adaptor while update is in progress.
│ │   GUIDs:              428ba8ba-40c8-4446-8d7a-394d6c28b26a
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  267
│       Minimum Version:  267
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341 ← UEFI\CRT_A9087D1044AD18F7A94916D284CBC01827CF23CD8F60B79072C9CAA1FEF4D649
│                         5971a208-da00-5fce-b5f5-1234342f9cf7 ← UEFI\CRT_A9087D1044AD18F7A94916D284CBC01827CF23CD8F60B79072C9CAA1FEF4D649&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Only version upgrades are allowed
│                         • Signed Payload
│
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    1.257.0.0
│     Vendor:             ST Microelectronics (TPM:STM)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
│                         bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
│                         70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
│                         06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
│     Device Flags:       • Internal device
│
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    1057227777
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               3b7f92a6-36d0-49ae-a2d1-272f9a067274
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
├─UEFI Device Firmware:
│     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Summary:            UEFI ESRT device
│     Current version:    16842760
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               22f913fe-81c7-4c25-a318-be4d7dd02724
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
├─UEFI Device Firmware:
│     Device ID:          f95c9218acd12697af946874bfe4239587209232
│     Summary:            UEFI ESRT device
│     Current version:    65541
│     Minimum Version:    65541
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               4bea12df-56e3-4cdb-97dd-f133768c9051
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
├─UEFI Device Firmware:
│     Device ID:          d96de5c124b60ed6241ebcb6bb2c839cb5580786
│     Summary:            UEFI ESRT device
│     Current version:    0
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               1181d859-c3be-4b1d-985a-b28dca6ba6d8
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
└─UEFI Device Firmware:
      Device ID:          f37fb01122dd62c773f4e84ec89737e059712d59
      Summary:            UEFI ESRT device
      Current version:    22552
      Minimum Version:    1
      Vendor:             DMI:LENOVO
      Update State:       Success
      GUID:               cfa38dd6-0165-4f00-ae3c-6207803cab0b
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
```

</details>

**System UEFI configuration**
Please provide the output of the following commands:

```shell
efibootmgr -v
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,0000,0002,0004,001B,0017,0018,0019,001A,001C
Boot0000* Pop!_OS 22.04 LTS     HD(1,GPT,3edc7bd4-745b-4fbc-9c85-ad8510fcdf94,0x1000,0xf8fff)/File(\EFI\SYSTEMD\SYSTEMD-BOOTX64.EFI)
Boot0001* Pop!_OS 22.04 LTS     HD(1,GPT,3edc7bd4-745b-4fbc-9c85-ad8510fcdf94,0x1000,0xf8fff)/File(\EFI\systemd\systemd-bootx64.efi)
Boot0002* Linux-Firmware-Updater        HD(1,GPT,3edc7bd4-745b-4fbc-9c85-ad8510fcdf94,0x1000,0xf8fff)/File(\EFI\pop\fwupdx64.efi)
Boot0004* Pop!_OS 21.10 HD(1,GPT,3edc7bd4-745b-4fbc-9c85-ad8510fcdf94,0x1000,0xf8fff)/File(\EFI\SYSTEMD\SYSTEMD-BOOTX64.EFI)
Boot0010  Setup FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu     FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen      FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics    FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  ThinkShield secure wipe       FvFile(3593a0d5-bd52-43a0-808e-cbff5ece2477)
Boot0015  Startup Interrupt Menu        FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0016  Rescue and Recovery   FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0017* USB CD        VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0 VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD0      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001B* USB HDD       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001C* PXE BOOT      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001D  Regulatory Information        FvFile(478c92a0-2622-42b7-a65d-5894169e4d24)
Boot001E* Boot Next Boot Option VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,a7ca6d35b2c2684783721826a7404894)
```

```shell
efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-428ba8ba-40c8-4446-8d7a-394d6c28b26a-0
```

```shell
tree /boot
/boot
├── config-5.15.0-1007-nvidia
├── config-5.17.5-76051705-generic
├── config-5.19.16-76051916-generic
├── efi  [error opening dir]
├── grub
│   ├── gfxblacklist.txt
│   └── unicode.pf2
├── initrd.img -> initrd.img-5.15.0-1007-nvidia
├── initrd.img-5.15.0-1007-nvidia
├── initrd.img-5.17.5-76051705-generic
├── initrd.img-5.19.16-76051916-generic
├── initrd.img-5.3.0-7648-generic
├── initrd.img.old -> initrd.img-5.19.16-76051916-generic
├── System.map-5.15.0-1007-nvidia
├── System.map-5.17.5-76051705-generic
├── System.map-5.19.16-76051916-generic
├── vmlinuz -> vmlinuz-5.15.0-1007-nvidia
├── vmlinuz-5.15.0-1007-nvidia
├── vmlinuz-5.17.5-76051705-generic
├── vmlinuz-5.19.16-76051916-generic
└── vmlinuz.old -> vmlinuz-5.19.16-76051916-generic
```

**Additional questions**

- Operating system and version: Pop!_OS 22.04
- Have you tried rebooting? many times
- Is this a regression? it's never worked for me
- Are you using an NVMe disk? yes
- Is secure boot enabled? no
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? Boot Order Lock is off

**Comment by mrhpearson** [comment]
Hi
Are you able to see any error messages at all during the install? Any possibility of grabbing a video in case something is displayed briefly?
Mark

**Comment by jrop** [comment]
For sure, here is a quick vid.  Sorry my camera was having trouble focusing...

https://youtu.be/DxTlzZFo-2g

**Comment by jrop** [comment]
Per a suggestion on the Arch Wiki, I tried updating one device at a time (even though there appears to be only one update available:

```sh
fwupdmgr update a45df35ac0e948ee180fe216a5f703f32dda163f
```

After rebooting, I was prompted to upload the following error report:

```yaml
ReportVersion: 2
MachineId: e0ceaa8524431b9762cfcdd657253965487d72888b6896d8005c627f4ada56fe
Metadata:
  DistroId: pop
  DistroVersion: "22.04"
Reports:
  - Checksum: 986204f404d51b9327f43d32f0eef7b55817aa3a
    ChecksumDevice:
      - c13ecee1c385cc0ba482b61d351c232a2101d347
    ReleaseId: null
    Protocol: org.uefi.capsule
    UpdateState: 3
    UpdateError: failed to run update on reboot
    Guid:
      - 428ba8ba-40c8-4446-8d7a-394d6c28b26a
    Plugin: uefi_capsule
    VersionOld: 0.1.5
    VersionNew: 0.1.41
    Flags: 574619947
    Created: 1666288752
    Modified: 1666322610
    Metadata:
      LastAttemptStatus: "0x0"
      TpmFamily: "2.0"
      LastAttemptVersion: "0x0"
      Pcr0_SHA1: c13ecee1c385cc0ba482b61d351c232a2101d347
      DistroVersion: "22.04"
      RuntimeVersion(org.freedesktop.fwupd): 1.8.0
      HostSku: LENOVO_MT_20UH_BU_Think_FM_ThinkPad T14s Gen 1
      BootMgrDesc: legacy
      UEFIUXCapsule: Enabled
      CpuArchitecture: x86_64
      SecureBoot: Disabled
      HostFamily: ThinkPad T14s Gen 1
      HostVendor: LENOVO
      RuntimeVersion(org.freedesktop.gusb): 0.3.10
      FwupdTainted: "False"
      RuntimeVersion(com.dell.libsmbios): "2.4"
      MissingCapsuleHeader: "False"
      CompileVersion(org.freedesktop.gusb): 0.3.10
      KernelVersion: 5.19.16-76051916-generic
      FwupdSupported: "True"
      TpmEventLog: |-
        0x00000008 0f954a1bf48be1bf5f6bb025415fa428c60196d3 [UgAxAEMARQBUADMANgBXAAAA]
        0x80000008 1320773be7acdddf0f501b2ecd50daaeb5bcd456 [AADACQAAAAAAABAAAAAAAA==]
        0x00000001 93f036585df0f35892ecdadea15102dee732aa01 [QUNQSSBEQVRB]
        0x00000001 b0469aa139a98ebeae9693588554bab11e19724c [QUNQSSBEQVRB]
        0x00000004 9069ca78e7450a285173431b3e52c5c25299e473 [AAAAAA==]
        PCR0: c13ecee1c385cc0ba482b61d351c232a2101d347
        PCR0: a7aa37dad87cad05d3184ce6f323c218fd5b421dfc2b5d8b1c3e9f61bdb7de13
      EspPath: /boot/efi
      HostProduct: 20UHCTO1WW
      BootTime: "1666288734"
      KernelName: Linux
      RuntimeVersion(org.freedesktop.fwupd-efi): "1.0"
      CapsuleApplyMethod: nvram
      LinuxLockdown: none
      Pcr0_SHA256: a7aa37dad87cad05d3184ce6f323c218fd5b421dfc2b5d8b1c3e9f61bdb7de13
      CompileVersion(com.hughsie.libjcat): 0.1.9
      EfivarNvramUsed: "34608"
      KernelCmdline: systemd.show_status=false
      DistroId: pop
      CompileVersion(org.freedesktop.fwupd): 1.8.0
      RuntimeVersion(org.kernel): 5.19.16-76051916-generic
```
